vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        kabis:
            uri_prefix: /uploads/kabis
            upload_destination: '%kernel.project_dir%/public/uploads/kabis'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
