vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        kbis:
            uri_prefix: /uploads/kbis
            upload_destination: '%kernel.project_dir%/public/uploads/kbis'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
