controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_message:
    path: /api/message
    controller: App\Controller\MessageController::getMessage
