#<<<<<<<<<<Start: Server Image Target>>>>>>>>>>#
FROM httpd:2 as server

COPY ./.docker/httpd/httpd.conf /usr/local/apache2/conf/httpd.conf

COPY --from=php /srv/app /srv/app
#<<<<<<<<<<End: Server Image Target>>>>>>>>>>#