name: Continuous Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
    
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Build and Push Docker Image
    #   run: |
    #     cd ApiPlatform
    #     docker build -t waterways-backend .
    #     docker tag waterways-backend ${{ secrets.DOCKER_USERNAME }}/waterways-backend:latest
    #     docker push ${{ secrets.DOCKER_USERNAME }}/waterways-backend:latest

    - name: Build and Push PHP Docker Image
      run: |
          cd ApiPlatform
          docker build -t ${{ secrets.DOCKER_USERNAME }}/waterways-backend-php -f Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/waterways-backend-php:latest
   
    - name: Build and Push Nginx Docker Image
      run: |
          cd ApiPlatform
          docker build -t ${{ secrets.DOCKER_USERNAME }}/waterways-backend-httpd -f Dockerfile.httpd .
          docker push ${{ secrets.DOCKER_USERNAME }}/waterways-backend-httpd:latest
   


    - name: Deploy to EC2 Instance
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }} 
        script: |
          docker network create mynetwork 
          docker volume create shared_data

          docker stop php
          docker rm php
          docker pull ${{ secrets.DOCKER_USERNAME }}/waterways-backend-php:latest
          docker run -d --name php --network=mynetwork -v shared_data:/srv/app/public -p 9000:9000 ${{ secrets.DOCKER_USERNAME }}/waterways-backend-php:latest

          docker stop waterways-backend-httpd
          docker rm waterways-backend-httpd
          docker pull ${{ secrets.DOCKER_USERNAME }}/waterways-backend-httpd:latest
          docker run -d --name waterways-backend-httpd --network=mynetwork -v shared_data:/srv/app/public -p 80:80 ${{ secrets.DOCKER_USERNAME }}/waterways-backend-httpd:latest


          
         
