name: Continuous Deployment

on:
  push:
    branches:
      - dev  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ec2_ssh_key.pem
        chmod 600 ec2_ssh_key.pem

    - name: Deploy to Production Server
      run: |
        ssh -o StrictHostKeyChecking=no -i "waterways-backend-ec2-key.pem" ubuntu@ec2-13-51-198-220.eu-north-1.compute.amazonaws.com
