name: deploy-container
on:
  push:
    branches:
      - main
    paths:
      - 'front/**'

defaults:
  run:
    working-directory: front
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Set up AWS CLI v2
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-north-1

    - name: Verify AWS CLI version
      run: aws --version

      # - uses: actions/checkout@v2
      # - run: npm install
      # - run: npm run build
      # - uses: chrislennon/action-aws-cli@v1.1
      # - run: aws s3 sync build/ s3://waterways.challenge/ 
      #   env:
      #     AWS_ACCESS_KEY_ID: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}