name: Deploy to S3

on:
  push:
    branches:
      - main
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

    #   - name: Install Dependencies
    #     run: npm install

    #   - name: Build
    #     run: npm run build

    #   - name: Upload Build Artifacts
    #     uses: actions/upload-artifact@v2
    #     with:
    #       name: build-artifacts
    #       path: build/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.S3_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.S3_AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Deploy to AWS S3
        run: aws s3 sync ./front/build s3://waterways.challenge/ --delete
