name: Continuous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15.4-alpine
        env:
          POSTGRES_DB: symfony
          POSTGRES_PASSWORD: root
          POSTGRES_USER: root
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Environment
      run: |
        cd Apiplatform
        docker-compose up -d

    - name: Install Dependencies
      run: |
        cd Apiplatform
        docker-compose exec php composer install --prefer-dist --no-progress --no-suggest

    - name: Check Symfony Requirements
      run: |
        cd Apiplatform
        docker-compose exec php symfony check:requirements

    - name: Run PHP Tests
      run: |
        cd Apiplatform
        docker-compose exec php ./bin/phpunit

