name: Integration continue

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
      - dev

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./front
            
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          # cache: 'npm'
            
      - name: Install Dependencies
        run: npm install
            
      - name: Launch Tests
        run: npm test

  notifty-success-on-discord:
    needs: frontend-test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Notify on Discord
        uses: SebastiaanZ/github-status-embed-for-discord@main
        with:
          webhook_id: '1234567890'  # Has to be provided as a string
          webhook_token: ${{ secrets.DISCORD_TOKEN }}

          # Optional arguments for PR-related events
          # Note: There's no harm in including these lines for non-PR
          # events, as non-existing paths in objects will evaluate to
          # `null` silently and the github status embed action will
          # treat them as absent.
          pr_author_login: ${{ github.event.pull_request.user.login }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_source: ${{ github.event.pull_request.head.label }}

  notify-error-on-discord:
    needs: frontend-test
    runs-on: ubuntu-latest
    if: failure()
      
    steps:
      - name: Notify on Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_TOKEN }}
          content: "Workflow ${{ github.workflow }} **failed** on commit ${{ github.sha }}."

