name: Integration continue

on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
      - dev

jobs:
  frontend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./front
            
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - if: ${{ steps.cache-npm.outputs.cache-hit != 'true' }}
        name: List the state of node modules
        continue-on-error: true
        run: npm list
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 17
          # cache: 'npm'
            
      - name: Install Dependencies
        run: npm install
            
      - name: Launch Tests
        run: npm test

  notifty-success-on-discord:
    needs: frontend-test
    runs-on: ubuntu-latest
    if: success()
    steps:
      - name: Notify on Discord
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_TOKEN }}
          status: ${{ job.status }}
          title: "Github Actions CI"
          description: "Build and deploy to GitHub Pages"
          image: ${{ secrets.EMBED_IMAGE }}
          color: 0x0000ff
          url: "https://github.com/sarisia/actions-status-discord"
          username: GitHub Actions
          avatar_url: ${{ secrets.AVATAR_URL }}

  notify-error-on-discord:
    needs: frontend-test
    runs-on: ubuntu-latest
    if: failure()
      
    steps:
      - name: Notify on Discord
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_TOKEN }}
          content: "Workflow ${{ github.workflow }} **failed** on commit ${{ github.sha }}."

